export const ANALYTICS_CONFIG = {
  schemaVersion: '0.2',
  trackerVersion: '0.2.0',
  collectorVersion: '0.2.0',
  sourceClassifierVersion: 2,
  consentPolicyVersion: '2',
  sessionTimeoutMs: 30 * 60 * 1000,
  quickExitSeconds: 10,
  flushIntervalMs: 4000,
  maxBatchSize: 20,
  maxQueueSize: 100,
  maxEventBodyBytes: 64 * 1024,
  maxPropertyStringLength: 256,
  maxCampaignStringLength: 160,
  allowedClockSkewFutureMs: 5 * 60 * 1000,
  maxClientEventAgeMs: 7 * 24 * 60 * 60 * 1000,
  siteHostname: 'www.permanentnybielsko.com',
  alternateSiteHostnames: ['permanentnybielsko.com', 'permanentnybielsko-astro.vercel.app'],
  priceView: {
    minimumVisibleRatio: 0.5,
    minimumVisibleMs: 1000,
  },
  pendingQueueStorageKey: 'pa_pending_v2',
} as const;
